name=mux-sensors-lib
version=1.0.0
author=Gabriel Bozelli Dias
maintainer=Gabriel Bozelli Dias <gbozelli@gmail.com>
sentence=Arduino library for CD74HC4067 analog multiplexers
paragraph=Provides efficient handling of up to 8 analog sensor channels using a single ADC pin, with configurable normalization and diagnostics.
category=Sensors
url=https://github.com/gbozelli/mux-sensors-lib
architectures=*
includes=mux_sensors_lib.h
license=MIT
